### ISSUE TITLE
Add work items to issues

### ISSUE THREAD

**Issue by yungyuc** [Sean20405/fftconvolve2d#2]
In your proposal there is [a plan](https://github.com/yungyuc/nsdhw_24au/blob/f80b9d4b7d7c522934b9f68e650184af4e3c9b7c/project/Sean20405/README.rst?plain=1#L114) to have CI set up around now.  I'd like to know how well you have progressed?  (This is a genuine question.  It is not a request for progress disguised as a question.)

I wonder if you can turn the work into trackable issues in this repository.  They do not need to be accurate.  They should help you better plan for the work and save you time.  What do you think?

**Comment by yungyuc** [comment]
Any update?

**Comment by Sean20405** [comment]
Sorry for late reply.

I was busy for one activity and other midterm exams for the past two weeks. So I may miss my schedule a lot. I'm still learning FFT now so I haven't add CI. I'll try my best to catch up the schedule.

As for opening issues for tracking progress, I haven't tried such things before, but it sounds useful. I'll give it a try when I start developing. Thanks!

**Comment by yungyuc** [comment]
Pay attention to your projects all the time.  You will be pulled in more directions after leaving the campus.  Consistent progress on what you do will bring you a more joyful career.

Feel free to close the issue when you see fit.
